version: "3.9"

services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/app:/home/jovyan/app
    env_file: ./jupyter/.env
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./api/app:/app
    env_file: ./api/.env
